# -*- coding: utf-8 -*-
"""BotTelegram

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rlYGxlXl88SubctMJN4dJCjq16hgs-oR
"""

! pip install pytelegrambotapi

import telebot

bot = telebot.TeleBot('1061502102:AAF6Rifkn7hTGpIerYzWqDUKq99BaQItbes')
keyboard1 = telebot.types.ReplyKeyboardMarkup()
keyboard1.row(telebot.types.InlineKeyboardButton('Добавить информацию'), telebot.types.InlineKeyboardButton('Пока')) 
keyboard1.row(telebot.types.InlineKeyboardButton('Прости меня'), telebot.types.InlineKeyboardButton('Найди мне девушку'))
keyboard1.row(telebot.types.InlineKeyboardButton('Давай общаться!'), telebot.types.InlineKeyboardButton('Нажми на меня'))

name = ' ';
surname = ' ';
age = 0;

@bot.message_handler(commands=['start'])
def start_message(message):
    bot.send_message(message.chat.id, 'Привет, ты запустил бота собственного производства и написал мне /start', reply_markup=keyboard1)
    bot.send_sticker(message.chat.id, 'CAADAgADFAAD15YZE3BSoUWff_VJFgQ')
    
@bot.message_handler(commands=['break'])
def start_message(message):
    bot.send_message(message.chat.id, 'Ты что, хочешь закончить разговор со мной???')

@bot.message_handler(commands=['sonechka'])
def start_message(message):
    bot.send_message(message.chat.id, 'Знаю одну красотку с таким именем ;) Вот кстати она - @sonchikkKkkkkk')
    
    
@bot.message_handler(content_types=['text'])
def send_text(message):
    if message.text.lower() == 'добавить информацию':
      bot.send_message(message.chat.id, 'Введите информацию:')
    elif message.text.lower() == 'пока':
      bot.send_message(message.chat.id, 'Прощай, создатель')
    elif message.text.lower() == 'прости меня':
      bot.send_sticker(message.chat.id, 'CAADAgADJQAD15YZE-Xaowmh_KFXFgQ')
    elif message.text.lower() == 'найди мне девушку':
      bot.send_sticker(message.chat.id, 'CAADAgAD9wMAAnKq5gSWftXG2UIifhYE')
      bot.send_message(message.chat.id, 'Это Марина, ей 43 года, двоё детей и жизнь такая себе')
      bot.send_message(message.chat.id, 'И зачем тебе вообще девушка?')
    elif message.text.lower() == 'давай общаться!':
      bot.send_message(message.chat.id, 'Давай! Как тебя зовут?')
      bot.register_next_step_handler(message, get_name);
    elif message.text.lower() == 'нажми на меня':
      bot.send_message(message.chat.id, 'https://imbt.ga/r22H7oD187', reply_markup=keyboard1)
      bot.send_message(message.chat.id, 'Пхп могила - Андроид сила')
    elif message.text.lower() == 'дурак':
      bot.reply_to(message, "Сам {!s}".format(message.text))
    elif message.text.lower() == 'сонечка самая красивая на свете':
      bot.reply_to(message, "Абсолютно с тобой согласен")
    elif message.text.lower() == 'что ты можешь сказать о маше':
      bot.reply_to(message, "Маша просто буба. Я в восторге от неё!!!")
    else:
      bot.send_message(-1001275337446, format(message.text))

@bot.message_handler(content_types=['photo'])
def text_handler(message):
    chat_id = message.chat.id
    bot.send_message(chat_id, 'Очень скучаю за этим самым милым человечком❤')
    
      
def get_name(message):
    global name;
    name = message.text;
    bot.send_message(message.from_user.id, 'Какая у тебя фамилия?')
    bot.register_next_step_handler(message, get_surname);
  
def get_surname(message):
    global surname;
    surname = message.text;
    bot.send_message(message.from_user.id, 'Сколько тебе лет?');
    bot.register_next_step_handler(message, get_age);
    
def get_age(message):
    global age;
    age = int(message.text);
#     if age == 0: 
#       try:
#            age = int(message.text)
#       except Exception:
#            bot.send_message(message.from_user.id, 'Введите цифрами, пожалуйста!');
           
#     while age == 0: 
#         try:
#              age = int(message.text) 
#         except Exception:
#              bot.send_message(message.from_user.id, 'Цифрами, пожалуйста');
    keyboard2 = telebot.types.InlineKeyboardMarkup(); 
    key_yes = telebot.types.InlineKeyboardButton(text='Да', callback_data='yes');
    keyboard2.add(key_yes); 
    key_no= telebot.types.InlineKeyboardButton(text='Нет', callback_data='no');
    keyboard2.add(key_no);
    question = 'Тебе '+str(age)+' лет, тебя зовут '+name+' '+surname+'?';
    bot.send_message(message.from_user.id, text=question, reply_markup=keyboard2)

@bot.message_handler(content_types=['photo'])
def send_photos(photo):
    bot.send_photo(-1001275337446, photo = 'https://telegram.org/img/t_logo.png')
    
@bot.callback_query_handler(func=lambda call: True)
def callback_worker(call):
    if call.data == "yes":
      bot.send_message(call.message.chat.id, 'Я тебя запомнил, мой дорогой друг' + ' ' + name)
    elif call.data == "no":
      bot.send_message(call.message.chat.id, 'Давай проверим информацию заново! Просто предложи общаться')
      
  

      
# @bot.message_handler(content_types=['sticker'])
# def sticker_id(message):
#     print(message)
      
    

bot.polling()